pipeline {
    agent any

    stages {
        stage('Clone Gay Repository') {
            steps {
                git branch: 'main', 
                url: "https://github.com/poommieiei/gay-jenkins.git"
            }
            post {
                success {
                    echo 'Cloned repository successfully.'
                }
                failure {
                    echo 'Failed to clone repository.'
                }
        }
        stage('Install Node.js') {
            steps {
                // ติดตั้ง Node.js (หากยังไม่ได้ติดตั้ง)
                sh 'curl -sL https://deb.nodesource.com/setup_16.x | bash -'
                sh 'apt-get install -y nodejs'
                echo 'Node.js installed.'
            }
        }
        stage('Build') {
            steps {
                // รันคำสั่ง shell สำหรับติดตั้ง dependencies
                sh 'npm install'

                echo 'Building...'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
                // เพิ่มคำสั่ง deploy ที่นี่
            }
        }
    }
}
