pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                git branch: "main", 
                url: "https://github.com/poommieiei/learn-jenkins.git"
            }
            post {
                success {
                    echo 'Code checked out successfully.'
                }
                failure {
                    echo 'Failed to checkout code.'
                }
            }
        }
        stage('Install Node.js') {
            steps {
                sh 'curl -sL https://deb.nodesource.com/setup_16.x | bash -'
                sh 'apt-get install -y nodejs'
                sh 'node -v'
            }
            post {
                success {
                    echo 'Node.js installed successfully.'
                }
                failure {
                    echo 'Failed to install Node.js.'
                }
            }
        }
        stage('Check Node.js version') {
            steps {
                sh 'node -v'
            }
            post {
                success {
                    echo 'Node.js version checked successfully.'
                }
                failure {
                    echo 'Failed to check Node.js version.'
                }
            }
        }
        stage('Install dependencies') {
            steps {
                sh 'cd test-jenkins && npm i'
            }
            post {
                success {
                    echo 'Dependencies installed successfully.'
                }
                failure {
                    echo 'Failed to install dependencies.'
                }
            }
        }
        stage('Merge Code') {
            when {
                branch 'develop'
            }
            steps {
                sh 'cd test-jenkins && git fetch origin'
                sh 'cd test-jenkins && git merge origin/develop'
            }
            post {
                success {
                    echo 'Code merged successfully.'
                }
                failure {
                    echo 'Failed to merge code.'
                }
            }
        }
    }
}
